import 'package:hive_flutter/hive_flutter.dart';
import '../models/muscle_group.dart';
import '../models/exercise_block.dart';
import '../models/day_block.dart';
import '../models/plan.dart';
import '../models/plan_day_instance.dart';
import '../models/workout_session.dart';
import '../models/set_log.dart';
import '../models/adapters.dart';

class StorageService {
  static const String muscleGroupBox = 'muscle_groups';
  static const String exerciseBlockBox = 'exercise_blocks';
  static const String dayBlockBox = 'day_blocks';
  static const String planBox = 'plans';
  static const String planDayInstanceBox = 'plan_day_instances';
  static const String workoutSessionBox = 'workout_sessions';
  static const String setLogBox = 'set_logs';
  static const String settingsBox = 'settings';

  static Future<void> init() async {
    await Hive.initFlutter();
    
    // Register adapters (will be generated by build_runner)
    // For now, we'll use TypeAdapters manually
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(MuscleGroupAdapter());
    }
    if (!Hive.isAdapterRegistered(1)) {
      Hive.registerAdapter(ExerciseBlockAdapter());
    }
    if (!Hive.isAdapterRegistered(2)) {
      Hive.registerAdapter(DayBlockAdapter());
    }
    if (!Hive.isAdapterRegistered(3)) {
      Hive.registerAdapter(PlanAdapter());
    }
    if (!Hive.isAdapterRegistered(4)) {
      Hive.registerAdapter(PlanDayInstanceAdapter());
    }
    if (!Hive.isAdapterRegistered(5)) {
      Hive.registerAdapter(SetLogAdapter());
    }
    if (!Hive.isAdapterRegistered(6)) {
      Hive.registerAdapter(WorkoutStatusAdapter());
    }
    if (!Hive.isAdapterRegistered(7)) {
      Hive.registerAdapter(WorkoutSessionAdapter());
    }

    // Open boxes
    await Hive.openBox<MuscleGroup>(muscleGroupBox);
    await Hive.openBox<ExerciseBlock>(exerciseBlockBox);
    await Hive.openBox<DayBlock>(dayBlockBox);
    await Hive.openBox<Plan>(planBox);
    await Hive.openBox<PlanDayInstance>(planDayInstanceBox);
    await Hive.openBox<WorkoutSession>(workoutSessionBox);
    await Hive.openBox<SetLog>(setLogBox);
    await Hive.openBox(settingsBox);
  }

  // Muscle Groups
  static Box<MuscleGroup> get muscleGroups => Hive.box<MuscleGroup>(muscleGroupBox);
  
  // Exercise Blocks
  static Box<ExerciseBlock> get exerciseBlocks => Hive.box<ExerciseBlock>(exerciseBlockBox);
  
  // Day Blocks
  static Box<DayBlock> get dayBlocks => Hive.box<DayBlock>(dayBlockBox);
  
  // Plans
  static Box<Plan> get plans => Hive.box<Plan>(planBox);
  
  // Plan Day Instances
  static Box<PlanDayInstance> get planDayInstances => Hive.box<PlanDayInstance>(planDayInstanceBox);
  
  // Workout Sessions
  static Box<WorkoutSession> get workoutSessions => Hive.box<WorkoutSession>(workoutSessionBox);
  
  // Set Logs
  static Box<SetLog> get setLogs => Hive.box<SetLog>(setLogBox);
  
  // Settings
  static Box get settings => Hive.box(settingsBox);

  static Future<void> clearAll() async {
    await muscleGroups.clear();
    await exerciseBlocks.clear();
    await dayBlocks.clear();
    await plans.clear();
    await planDayInstances.clear();
    await workoutSessions.clear();
    await setLogs.clear();
  }
}

